all:
  children:
    wireguard_full_mesh:
      hosts:
        wg-node1:
          ansible_host: 192.168.64.3
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          wireguard_vpn_ip: 10.100.0.1
          wireguard_endpoint: 192.168.64.3
        wg-node2:
          ansible_host: 192.168.64.4
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          wireguard_vpn_ip: 10.100.0.2
          wireguard_endpoint: 192.168.64.4
        wg-node3:
          ansible_host: 192.168.64.7
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          wireguard_vpn_ip: 10.100.0.3
          wireguard_endpoint: 192.168.64.7
