---
# Vietcgi Customer Inventory
# Production servers

all:
  vars:
    ansible_user: "kevin"
    ansible_ssh_private_key_file: "~/.ssh/vietcgi_prod_key"
    ansible_python_interpreter: "/usr/bin/python3"

  children:
    app_servers:
      hosts:
        # Production Web Servers
        web-prod-01:
          ansible_host: "108.181.38.69"
          app_framework: "nodejs"
          app_name: "portal"

        # web-prod-02:
        #   ansible_host: "203.0.113.11"
        #   app_framework: "nodejs"
        #   app_name: "portal"

    mail_servers:
      hosts:
        # Production Mail Server (KumoMTA)
        web-prod-01:
          ansible_host: "108.181.38.69"

    # database_servers:
    #   hosts:
    #     db-prod-01:
    #       ansible_host: "203.0.113.30"
