---
# KumoMTA Service Handlers

- name: restart kumomta
  ansible.builtin.systemd:
    name: kumomta.service
    state: restarted
    daemon_reload: false
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    daemon_reload: false
  become: true
