---
# KumoMTA Service Handlers

- name: Restart kumomta
  ansible.builtin.systemd:
    name: kumomta.service
    state: restarted
    daemon_reload: false
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    daemon_reload: false
  become: true
