---
galaxy_info:
  role_name: pfsense_wireguard
  author: Kevin Vu
  description: Configure WireGuard VPN tunnels on pfSense using pfsensible.core
  company: vietcgi

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: FreeBSD
      versions:
        - all

  galaxy_tags:
    - pfsense
    - wireguard
    - vpn
    - networking
    - firewall
    - security

dependencies:
  - role: pfsensible.core
