---
# ansible-infra - Staging Inventory

all:
  vars:
    ansible_user: ubuntu
    ansible_port: 22
    common_hostname_environment: staging
    monitoring_grafana_enabled: true

  children:
    staging_servers:
      hosts:
        staging-web01.local:
          ansible_host: 10.1.1.10
        staging-db01.local:
          ansible_host: 10.1.2.10
