---
# Auth0 Test Inventory
# Testing against mock Auth0 API (no actual servers needed)

all:
  vars:
    ansible_connection: "local"
    ansible_python_interpreter: "/usr/bin/python3"

  hosts:
    localhost:
      ansible_host: "127.0.0.1"
